name: kindle_clone_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.1.2
  path_provider: ^2.1.5
  pdf: ^3.0.1
  syncfusion_flutter_pdfviewer: ^29.2.10
  open_filex: ^4.7.0
  flutter_image: ^4.0.0
  provider: ^6.0.5
  isar:
    hosted:
      name: isar
      url: https://pub.isar-community.dev/
    version: ^3.0.0

  isar_flutter_libs:
    hosted:
      name: isar_flutter_libs
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator:
    hosted:
      name: isar_generator
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
